$time = Measure-Command {
    $path = ".\trawler.ps1"

    if (Test-Path $path) {
        Clear-Content $path -Force
    }

    Add-Content -Path $path -Value (Get-Content .\src\AutogeneratedBanner.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Parameters.ps1)

    foreach ($file in (Get-ChildItem .\src\Helpers)) {
        Add-Content -Path $path -Value (Get-Content $file.FullName)
    }

    foreach ($file in (Get-ChildItem .\src\Paths)) {
        Add-Content -Path $path -Value (Get-Content $file.FullName)
    }

    foreach ($file in (Get-ChildItem .\src\Techniques)) {
        Add-Content -Path $path -Value (Get-Content $file.FullName)
    }

    Add-Content -Path $path -Value (Get-Content .\src\Detections.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Snapshots.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Drives.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Common.ps1)
}

Write-Host "Built in: $($time.TotalSeconds) seconds"