param(
    [string]
    $TechniqueFilter = "*"
)
$time = Measure-Command {
    $path = ".\trawler.ps1"

    if (Test-Path $path) {
        Clear-Content $path -Force
    }

    Add-Content -Path $path -Value (Get-Content .\src\Common\AutogeneratedBanner.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Common\Parameters.ps1)

    foreach ($file in (Get-ChildItem .\src\Techniques -Filter $TechniqueFilter)) {
        Add-Content -Path $path -Value "#region Technique: $($file.Name.Trim(".ps1"))"
        Add-Content -Path $path -Value (Get-Content $file.FullName)
        Add-Content -Path $path -value "#endregion"
    }

    Add-Content -Path $path -Value (Get-Content .\src\Common\Detections.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Common\EventLog.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Common\HelperFunctions.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Common\DriveChanges.ps1)
    Add-Content -Path $path -Value (Get-Content .\src\Common\MainFunctionality.ps1)
}

Write-Host "Built in: $($time.TotalSeconds) seconds"